export const DUMMY_DATA = [
  {
    headings: [
      {
        id: 103,
        code: "booking_sales_tax",
        label: "SALES TAX",
        show: true,
        ordering: 0,
      },
      {
        id: 250,
        code: "service_type_section",
        label: "CHOOSE SERVICE TYPE",
        show: false,
        ordering: 1,
      },
      {
        id: 90,
        code: "service_section",
        label: "Choose Your Service",
        show: true,
        ordering: 2,
      },
      {
        id: 91,
        code: "extras_section",
        label: "Select Extras",
        show: true,
        ordering: 3,
      },
      {
        id: 94,
        code: "frequency_section",
        label: "How Often Should We Come?",
        show: true,
        ordering: 4,
      },
      {
        id: 88,
        code: "you_are_section",
        label: "Contact Information",
        show: true,
        ordering: 5,
      },
      {
        id: 89,
        code: "your_home_section",
        label: "Service Address",
        show: true,
        ordering: 6,
      },
      {
        id: 93,
        code: "service_date_section",
        label: "When Would You Like Us To Come?",
        show: true,
        ordering: 7,
      },
      {
        id: 92,
        code: "discount_code_section",
        label: "Discount Code",
        show: true,
        ordering: 8,
      },
      {
        id: 98,
        code: "payment_section",
        label: "Payment Details",
        show: true,
        ordering: 9,
      },
      {
        id: 95,
        code: "custom_fields_section",
        label: "CUSTOM FIELDS",
        show: false,
        ordering: 10,
      },
      {
        id: 96,
        code: "customer_notes_section",
        label: "Anything Else We Should Know?",
        show: true,
        ordering: 11,
      },
      { id: 97, code: "tip_section", label: "TIP", show: false, ordering: 12 },
      {
        id: 99,
        code: "booking_summary",
        label: "SUMMARY",
        show: false,
        ordering: 13,
      },
      {
        id: 100,
        code: "booking_subtotal",
        label: "SUB-TOTAL",
        show: true,
        ordering: 14,
      },
      { id: 101, code: "booking_tip", label: "TIP", show: false, ordering: 15 },
      {
        id: 102,
        code: "booking_discount",
        label: "DISCOUNT",
        show: true,
        ordering: 16,
      },
      {
        id: 236,
        code: "booking_today_total",
        label: "First Service Total",
        show: true,
        ordering: 17,
      },
      {
        id: 241,
        code: "booking_next_total",
        label: "Future Service Total",
        show: true,
        ordering: 18,
      },
      {
        id: 104,
        code: "booking_total",
        label: "TOTAL",
        show: true,
        ordering: 19,
      },
    ],
    paragraphs: {
      address_information: {
        id: 125,
        text: "Where would you like us to clean?",
        show: true,
      },
      agreement_information: {
        id: 132,
        text: "By clicking the Book Now button you are agreeing to our Terms of Service and Privacy Policy.",
        show: true,
      },
      booking_summary_duration: { id: 134, show: true },
      complete_your_booking: {
        id: 133,
        text: "Book Your Cleaning Service Now",
        show: true,
      },
      contact_information: {
        id: 124,
        text: "Let us know how we can reach you.",
        show: true,
      },
      discount_code_information: {
        id: 128,
        text: "If you have a discount code, enter it here",
        show: false,
      },
      extra_information: {
        id: 129,
        text: "Select any additional items you need cleaned. We recommend a deep cleaning if your home hasn't been regularly maintained. Any add-ons must be selected with all types of cleanings.",
        show: true,
      },
      few_details: {
        id: 123,
        text: "Let Us  Know What We Can Do For You.",
        show: true,
      },
      payment_information: {
        id: 131,
        text: "Enter your card information below. Don't worry, you won't be charged until after service has been rendered.",
        show: true,
      },
      schedule_information: {
        id: 130,
        text: "You can change this at any time. Recurring discounts apply after the first cleaning.",
        show: true,
      },
      service_date_information: {
        id: 127,
        text: "Please choose a date and time that works for you. If your preferred time isn't listed feel free to call us to see if we can make it work.",
        show: true,
      },
      service_information: {
        id: 126,
        text: "Our flat rate pricing applies to whole home cleanings. For extra large or extra dirty homes the price may be more. For partial home cleans please call us.",
        show: true,
      },
      service_type_information: {
        id: 252,
        text: "What type of service would you like?",
        show: false,
      },
    },
    system_fields: {
      address: {
        id: 12,
        label: "Address*",
        show: true,
        value_required: true,
        ordering: 19,
      },
      apt_suite: {
        id: 60,
        label: "Apt/Suite #",
        show: true,
        value_required: false,
        ordering: 20,
      },
      cash_payment: {
        id: 184,
        label: "Cash",
        show: true,
        value_required: false,
        ordering: 0,
      },
      check_payment: {
        id: 185,
        label: "Check",
        show: true,
        value_required: false,
        ordering: 0,
      },
      city: {
        id: 13,
        label: "City*",
        show: true,
        value_required: true,
        ordering: 21,
      },
      credit_card_cvc: {
        id: 62,
        label: "Card CVC*",
        show: true,
        value_required: true,
        ordering: 33,
      },
      credit_card_expires: {
        id: 63,
        label: "MM/YYYY*",
        show: true,
        value_required: true,
        ordering: 34,
      },
      credit_card_number: {
        id: 61,
        label: "**** **** **** *****",
        show: true,
        value_required: true,
        ordering: 32,
      },
      credit_card_payment: {
        id: 183,
        label: "Credit Card",
        show: true,
        value_required: false,
        ordering: 0,
      },
      customer_notes: {
        id: 19,
        label: "Please provide any special instructions here.",
        show: true,
        value_required: false,
        ordering: 36,
      },
      discount_code: {
        id: 18,
        label: "Discount Code (or leave this blank) *",
        show: true,
        value_required: false,
        ordering: 29,
      },
      email: {
        id: 10,
        label: "Email*",
        show: true,
        value_required: true,
        ordering: 14,
      },
      first_name: {
        id: 8,
        label: "First Name*",
        show: true,
        value_required: true,
        ordering: 12,
      },
      frequency: {
        id: 20,
        label: "Frequency *",
        show: true,
        value_required: true,
        ordering: 21,
      },
      frequency_summary: {
        id: 188,
        label: "Select frequency...",
        show: true,
        value_required: false,
        ordering: 55,
      },
      last_name: {
        id: 9,
        label: "Last Name*",
        show: true,
        value_required: true,
        ordering: 13,
      },
      paypal_payment: {
        id: 186,
        label: "Paypal",
        show: true,
        value_required: false,
        ordering: 0,
      },
      phone: {
        id: 11,
        label: "Phone*",
        show: true,
        value_required: true,
        ordering: 15,
      },
      service: {
        id: 16,
        label: "Type of Service *",
        show: true,
        value_required: true,
        ordering: 13,
      },
      service_date: {
        id: 182,
        label: "Click to Choose a Date",
        show: true,
        value_required: false,
        ordering: 26,
      },
      service_date_summary: {
        id: 187,
        label: "Choose service date...",
        show: true,
        value_required: false,
        ordering: 53,
      },
      service_type: {
        id: 255,
        label: "Type of Service",
        show: false,
        value_required: false,
        ordering: 12,
      },
      service_workers: {
        id: 26,
        label: "Cleaner",
        show: true,
        value_required: false,
        ordering: 25,
      },
      sms_notifications: {
        id: 25,
        label: "Send me reminders about my booking via text message",
        show: false,
        value_required: false,
        default_value: false,
        ordering: 16,
      },
      state: {
        id: 14,
        label: "State*",
        show: true,
        value_required: true,
        ordering: 22,
      },
      tip: {
        id: 24,
        label: "Tip",
        show: false,
        value_required: false,
        ordering: 38,
      },
      zip: {
        id: 15,
        label: "Zip Code*",
        show: true,
        value_required: true,
        ordering: 23,
      },
    },
    content_areas: {
      content_area: {
        id: 121,
        html: '\n\n\n\u003cdiv class="form_section text-center" id="content_panel" style="box-sizing: border-box; text-align: center; padding: 30px 0px 0px; border-radius: 2px; color: rgb(171, 171, 171); font-family: proxima, arial; font-size: 16px; line-height: 22.8571434020996px; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"\u003e\n\u003cdiv class="icon-sidebar"\u003e\u003csvg class="clock" enable-background="new 0 0 281.965 281.965" height="28px" role="img" viewBox="0 0 281.965 281.965" width="28px" x="0px" xml:space="preserve" y="0px"\u003e\u003cuse xlink:href="https://maidcomplete.launch27.com/images/tenant/form/icons.svg#clock"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/div\u003e\n\n\u003ch4 style="box-sizing: border-box; font-family: inherit; font-weight: bold; line-height: 1.1; color: rgb(55, 62, 74); margin-top: 8.5px; margin-bottom: 8.5px; padding: 0px 20px;"\u003eSAVES YOU TIME\u003c/h4\u003e\n\n\u003cp style="box-sizing: border-box; margin: 0px 0px 8.5px; padding: 0px 20px 40px; font-weight: lighter; font-family: proxima,arial; color: rgb(171, 171, 171);"\u003eMaid Complete helps you live smarter, giving you time to focus on what\'s most important.\u003c/p\u003e\n\n\u003cdiv class="icon-sidebar"\u003e\u003csvg class="shield" enable-background="new 0 0 212.59 296.004" height="31px" role="img" viewBox="0 0 212.59 296.004" width="28px" x="0px" xml:space="preserve" y="0px"\u003e\u003cuse xlink:href="https://maidcomplete.launch27.com/images/tenant/form/icons.svg#shield"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/div\u003e\n\n\u003ch4 style="box-sizing: border-box; font-family: inherit; font-weight: bold; line-height: 1.1; color: rgb(55, 62, 74); margin-top: 8.5px; margin-bottom: 8.5px; padding: 0px 20px;"\u003eSAFETY FIRST\u003c/h4\u003e\n\n\u003cp style="box-sizing: border-box; margin: 0px 0px 8.5px; padding: 0px 20px 40px; font-weight: lighter; font-family: proxima,arial; color: rgb(171, 171, 171);"\u003eWe rigorously vet all of our cleaners, who undergo identity and background checks.\u003c/p\u003e\n\n\u003cdiv class="icon-sidebar"\u003e\u003csvg class="thumb-up" enable-background="new 0 0 286.198 266.346" height="25px" role="img" viewBox="0 0 286.198 266.346" width="28px" x="0px" xml:space="preserve" y="0px"\u003e\u003cuse xlink:href="https://maidcomplete.launch27.com/images/tenant/form/icons.svg#thumb-up"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/div\u003e\n\n\u003ch4 style="box-sizing: border-box; font-family: inherit; font-weight: bold; line-height: 1.1; color: rgb(55, 62, 74); margin-top: 8.5px; margin-bottom: 8.5px; padding: 0px 20px;"\u003eONLY THE BEST QUALITY\u003c/h4\u003e\n\n\u003cp style="box-sizing: border-box; margin: 0px 0px 8.5px; padding: 0px 20px 40px; font-weight: lighter; font-family: proxima,arial; color: rgb(171, 171, 171);"\u003eOur professional cleaners go above and beyond on every job. Cleaners are rated and reviewed after each cleaning.\u003c/p\u003e\n\n\u003cdiv class="icon-sidebar"\u003e\u003csvg class="cleaning-bottle" enable-background="new 0 0 165.503 284.223" height="39px" role="img" viewBox="0 0 165.503 284.223" width="23px" x="0px" xml:space="preserve" y="0px"\u003e\u003cuse xlink:href="https://maidcomplete.launch27.com/images/tenant/form/icons.svg#cleaning-bottle"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/div\u003e\n\n\u003ch4 style="box-sizing: border-box; font-family: inherit; font-weight: bold; line-height: 1.1; color: rgb(55, 62, 74); margin-top: 8.5px; margin-bottom: 8.5px; padding: 0px 20px;"\u003eEASY TO GET HELP\u003c/h4\u003e\n\n\u003cp style="box-sizing: border-box; margin: 0px 0px 8.5px; padding: 0px 20px 40px; font-weight: lighter; font-family: proxima,arial; color: rgb(171, 171, 171);"\u003eSelect the number of bedrooms and bathrooms, date and relax while we take care of your home.\u003c/p\u003e\n\n\u003cdiv class="icon-sidebar"\u003e\u003csvg class="bubble" enable-background="new 0 0 309.063 268" height="29px" role="img" viewBox="0 0 309.063 268" width="33px" x="0px" xml:space="preserve" y="0px"\u003e\u003cuse xlink:href="https://maidcomplete.launch27.com/images/tenant/form/icons.svg#bubble"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/div\u003e\n\n\u003ch4 style="box-sizing: border-box; font-family: inherit; font-weight: bold; line-height: 1.1; color: rgb(55, 62, 74); margin-top: 8.5px; margin-bottom: 8.5px; padding: 0px 20px;"\u003eSEAMLESS COMMUNICATION\u003c/h4\u003e\n\n\u003cp style="box-sizing: border-box; margin: 0px 0px 8.5px; padding: 0px 20px 40px; font-weight: lighter; font-family: proxima,arial; color: rgb(171, 171, 171);"\u003eCall, email or online chat us anytime! Our average response time is under 10 minutes.\u003c/p\u003e\n\n\u003cdiv class="icon-sidebar"\u003e\u003csvg class="visa" enable-background="new 0 0 378 235" height="21px" role="img" viewBox="0 0 378 235" width="31px" x="0px" xml:space="preserve" y="0px"\u003e\u003cuse xlink:href="https://maidcomplete.launch27.com/images/tenant/form/icons.svg#visa"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/div\u003e\n\n\u003ch4 style="box-sizing: border-box; font-family: inherit; font-weight: bold; line-height: 1.1; color: rgb(55, 62, 74); margin-top: 8.5px; margin-bottom: 8.5px; padding: 0px 20px;"\u003eCASH FREE PAYMENT\u003c/h4\u003e\n\n\u003cp style="box-sizing: border-box; margin: 0px 0px 8.5px; padding: 0px 20px 40px; font-weight: lighter; font-family: proxima,arial; color: rgb(171, 171, 171);"\u003ePay securely online only when the cleaning is complete. 256-bit SSL encryption technology.\u003c/p\u003e\n\u003c/div\u003e\n\n\n\n',
        show: true,
      },
    },
    settings: {
      submit_button: { button_text: "Book Now" },
      apply_button: { button_text: "Apply" },
      form: {
        background_image: "",
        background_type: "transparent",
        panel_color: "#ffffff",
        primary_color: "#ff8604",
        secondary_color: "#ff8604",
        label_color: "",
        label_font: "",
        text_color: "#ababab",
        text_font: "proxima,arial",
        heading_color: "#373e4a",
        heading_font: "proxima,arial",
        hide_sidebar: false,
        service_block_type: "dropdown",
        service_summary_type: "default",
        custom_css:
          "Ym9keS53aWRnZXQgLmJvb2tpbmdfZm9ybSB7IG1heC13aWR0aDogMTAwJSB9",
      },
    },
  },
];

// console.log(DUMMY_DATA[0].headings);
export const DUMMYITEMSTHREE = [
  {
    id: 10,
    name: "radio",
    label: "deep cleaning",
    value: 59.0,
    description: "",
  },
  {
    id: 7,
    name: "radio",
    label: "clean inside kitchen cabinets",
    value: 30.0,
    description: "",
  },
  {
    id: 5,
    name: "radio",
    label: "finished basement",
    value: 60.0,
    description: "",
  },
  {
    id: 11,
    name: "radio",
    label: "we have pets",
    value: 10.0,
    description: "",
  },
  {
    id: 4,
    name: "radio",
    label: "clean inside windows",
    value: 61.0,
    description: "",
  },
];
console.log(DUMMYITEMSTHREE);